CREATE DATABASE bank;
SHOW DATABASES;

USE bank;
CREATE TABLE customers_details(

CUSTOMER_NAME VARCHAR(20),
CUSTOMER_MOBILE INT,
CUSTOMER_BALANCE DECIMAL,
CUSTOMER_ACCOUNT_NO BIGINT(30),
CUSTOMER_NOMINEE VARCHAR(20)

);
SHOW TABLES;
DESCRIBE customer_details;
SELECT*FROM customers_details;
INSERT INTO customers_details VALUES('RANJITHA',80737212,12000,12345678962,'HARSHITHA');
INSERT INTO customers_details VALUES('HARSHITHA',80737212,12000,12345678962,'RANJITHA');
INSERT INTO customers_details(CUSTOMER_NAME,CUSTOMER_MOBILE,CUSTOMER_NOMINEE)VALUES('SUNITHA',80737212,'HARSHITHA');
 
USE bank;
CREATE  TABLE employees_details(
EMPLOYEE_NAME VARCHAR(20),
EMPLOYEE_MOBILE INT,
EMPLOYEE_EMAIL VARCHAR(30),
EMPLOYEE_DESIGNATION VARCHAR(30)

);
SHOW TABLES;
DESCRIBE employees_details;
SELECT*FROM employees_details;
INSERT INTO employees_details VALUES('RANJITHA',80737212,'ranjitham.xworkz@gmail.com','MANAGER');
INSERT INTO employees_details VALUES('SUNITHA',80990033,'sunitha.xworkz@gmail.com','TECHNICIAN');
INSERT INTO employees_details VALUES('HARSHITHA',99004455,'harshitha.xworkz@gmail.com','CASHIER');
INSERT INTO employees_details VALUES('PAVITHRA',77008855,'pavitra.xworkz@gmail.com','MD');
INSERT INTO employees_details(EMPLOYEE_NAME,EMPLOYEE_MOBILE,EMPLOYEE_EMAIL)VALUES('DEVIKA',80737212,'devika@gmail.com');

